### ISSUE TITLE
API Testing-User is getting registered with username containing spaces

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-5#43]
Hi Merry,

-User is getting registered if Username is having spaces

Steps to Reproduce:

1)Open postman and send post request for register
2)In Body(raw),fill all fields with valid input and have spaces in username
![5](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/895a7dd5-25fa-4b33-9632-caa34328f23a)
![6](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/10d2eae0-fb9e-42a2-9e64-2a70e21d61bb)

3)Response is received: 201:created and message appears as : User registered

Below are the screenshots attached.

**Comment by Jebisha123** [comment]
Resolved

**Comment by priyadhawan06** [comment]
Issue is resolved.
![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/ab23087e-91c5-4ab2-95b7-5b3a7029fcf0)
