### ISSUE TITLE
 Valid Email Format with only .com

### ISSUE THREAD

**Issue by reshuripple** [Ripples2023/Ripples2023Repo-Sprint-5#50]
based on the design doc  Valid Email Format with only .com domain should take but its taking other domain too.

{
   
    "firstName": "reshu",
     "email":"reshu@gmail.in",
    "lastName":"jainp",
    "password":"reghghyuyusu",
    "username":"reshujain"    
}

**Comment by reshuripple** [comment]
user is registered without any specific email format for eg: reshughg@demo.com

**Comment by Jebisha123** [comment]
Resolved

**Comment by reshuripple** [comment]
tested and working fine ....closing the issue
