### ISSUE TITLE
user name field is not unique

### ISSUE THREAD

**Issue by reshuripple** [Ripples2023/Ripples2023Repo-Sprint-5#52]
if we give same email and keep changing other field

    "firstName": "mira",
     "email":"Mirabai@gmail.com",
    "lastName":"baimira",
    "password":"miraalwar@@",
    "username":"Mirabai123"    

    "firstName": "mira",
     "email":"Mirabai@gmail.com",
    "lastName":"baimira",
    "password":"miraalwar@@",
    "username":"Mirasinghi123"

**Comment by Jebisha123** [comment]
Resolved

**Comment by reshuripple** [comment]
Tested and closing
