### ISSUE TITLE
API Testing-All domain names are getting accepted in addition to (.com)

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-5#54]
Hi @Jebisha123 ,

-All domain names are getting accepted in addition to (.com)

Steps to Reproduce:
Enter valid Firstname, Lastname, Password, Confirm password,Username and enter invalid Email format eg: manishaanmol344@brazil.fr
User is getting registered with this invalid format.

Screenshots attached
![11](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/b9979120-d1e4-44df-84b4-ff3f09da667e)
![12](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/11914394-184b-4960-9e4d-e6e5d5cc3fda)

**Comment by Jebisha123** [comment]
Resolved

**Comment by priyadhawan06** [comment]
Working fine,So closing this defect.

![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/fb97ff63-3bf9-4050-86fd-d706ea1748c8)
