### ISSUE TITLE
API Testing-Password with spaces is getting accepted

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-5#55]
Hi Merry,

-User is getting registered if Password is having spaces

Steps to Reproduce:
1)Open postman and send post request for register
2)In Body(raw),fill all fields with valid input and have spaces in password
3)Response is received: 201:created and message appears as : User registered

Attaching screenshot
![33](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/233cfe42-9dc6-4691-9c75-01c241d1fb3f)
:

**Comment by Jebisha123** [comment]
Resolved

**Comment by priyadhawan06** [comment]
Issue is resolved.So,closing this defect.

![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/6421cc8d-3101-403a-9e93-a760be1614e0)
