### ISSUE TITLE
Bug on all invalid and  all mandatory field.

### ISSUE THREAD

**Issue by nisha552** [Ripples2023/Ripples2023Repo-Sprint-5#56]
Test case:- API should not accepts invalid inputs for all Sign-Up fields

Bug Description: For all invalid inputs only shows error message for FirstName, LastName and Email  not for Username  password fields.

![1 invalid inputs](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/102511041/dddff91d-67bf-41be-aa14-351336aa6024)

**Comment by nisha552** [comment]
test case:  all input fields are mandatory
Bug Description: Only display error message for Email and username , not for first name , last name , username. It should display message for all mandatory fields.
![2 invalid inputs](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/102511041/9c9859f1-53f8-4902-b0c2-9c891bfa7910)

**Comment by nisha552** [comment]
Test Case: user should not register by keeping  First name  mandatory 
Bug Description: User registered by keeping first name blank(mandatory
![3 Blank--mandatory first name](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/102511041/05591c57-82bc-45df-b0f6-9e58eb7d7b9b)
)

**Comment by nisha552** [comment]
Verify API should not accepts invalid inputs for all Sign-Up fields

Bug description: Now for all invalid inputs only shows error message for FirstName, LastName and Email ,Username and not for 
![new 1](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/102511041/e2abf8d1-da21-47cc-9a7d-0d207154ba6e)
Password fields.

**Comment by nisha552** [comment]
Validate all input fields are mandatory
Bug description: Shows result message for firstname, lastname, email, username but not for the password
![new 2](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/102511041/3dbabb33-2b5c-4591-9423-787377f702b6)

**Comment by Jebisha123** [comment]
Since  Password is encrypted password size error message reflects only if all the other fields are given with vaild input

**Comment by nisha552** [comment]
Retest 
Resolved bug
