### ISSUE TITLE
API-Testing:User is getting registered if Password is kept blank with spaces(starting from 8 length)

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-5#57]
Hi @Jebisha123 ,

 User is getting registered if Password is kept blank with spaces(starting from 8 length)

Steps to Reproduce:

1)Enter valid firstname,Lastname, Username,Password
2)Leave Password blank by clicking spacebar 8 times

Attaching Screenshot:
![23](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/14d21784-dbdd-4198-86ff-bc0ddb43b75c)

**Comment by Jebisha123** [comment]
Resolved

**Comment by priyadhawan06** [comment]
error message is now reflecting for blank password field.So,closing this defect.
![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/7bf24f20-bb79-42df-aa3d-69c697c86373)
