### ISSUE TITLE
ApI testing: user registered by keeping first name , last name field blank 

### ISSUE THREAD

**Issue by nisha552** [Ripples2023/Ripples2023Repo-Sprint-5#58]
Test Case: user should not register by keeping  First name  mandatory 
Bug Description: User registered by keeping first name blank(mandatory
![3 Blank--mandatory first name](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/102511041/05591c57-82bc-45df-b0f6-9e58eb7d7b9b)

**Comment by nisha552** [comment]
Test case: user should not registered by keeping any one or two  fields blank
Bug description: user registered by keeping first name, last name blank but not for keeping email, uername , password  field blank
![4 keep two field blank](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/102511041/b49b3478-82bc-4e7c-90cc-4b5424f42abc)

**Comment by nisha552** [comment]
Test case: user should not registered by keeping any one or two fields blank

Bug description: user registered by keeping first name, last name blank but not for keeping email, us

**Comment by Jebisha123** [comment]
Resolved and updated code in github

**Comment by nisha552** [comment]
Ok.
