### ISSUE TITLE
API Testing: Error messages for all fields are not reflecting if all fields are kept blank by spacing

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-5#59]
Hi @Jebisha123 ,

Error messages for all fields are not reflecting if all fields are kept blank by spacing

Steps to Reproduce:
1)Go to postman
2)For POST request,enter url
3)Leave all inputs blank with spaces from 8 till 16

error messages for few fields are reflecting

Screenshots attached:
![32](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/33b09189-fb03-49e9-b441-744211d53d28)

**Comment by Jebisha123** [comment]
Resolved

**Comment by priyadhawan06** [comment]
Error messages reflecting for all fields.So,closing this defect

![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/b9a75112-15a1-41fe-838f-4447bc393eee)
