### ISSUE TITLE
API-Testing:Error messages for all fields are not reflecting if all fields are kept blank 

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-5#60]
Hi @Jebisha123 ,

Error messages for all fields are not reflecting if all fields are kept blank

Steps to Reproduce:
1)Go to postman
2)For POST request,enter url
3)Leave all inputs blank 
![ss](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/ae05abba-550e-451e-98f6-ef9c4e49c254)

error messages for few fields are reflecting

Screenshots attached:

**Comment by Jebisha123** [comment]
Resolved

**Comment by priyadhawan06** [comment]
error messages for all blank fields are now reflecting.So,closing this issue.

![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/f770e363-5ac2-488c-a3f6-60b5cf6fdeca)
