### ISSUE TITLE
API Testing:Username is accepting special characters and user is getting registered

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-5#61]
Username is accepting special characters and user is getting registered

Steps to Reproduce: 
)Go to postman
2)For POST request,enter url
3)Enter invalid username by inserting special characters
![sp](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/5ed64877-c20c-4c9c-ae39-745dc7c30427)
![spp](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/1d24dfdb-98cd-4348-a918-a184d09420be)

Attaching screenshots:

**Comment by Jebisha123** [comment]
Resolved

**Comment by priyadhawan06** [comment]
working fine,So closing this defect.

![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/52229b3b-cbfb-4046-ad11-c938f822a631)
