### ISSUE TITLE
API Testing: Space accepted in Username and Password field

### ISSUE THREAD

**Issue by nisha552** [Ripples2023/Ripples2023Repo-Sprint-5#63]
Test case: Username should not accept space
Test case: Password should not accept space
Bug description : User able to registered with space in username and password 
![5 password space](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/102511041/8336bc04-8379-4c4d-864e-16a04ccec02d)
 but for other field it display error message

**Comment by Jebisha123** [comment]
Resolved

**Comment by nisha552** [comment]
Retest
Space not accepted in username and password field as expected
Close issue
