### ISSUE TITLE
API Testing: Special characters accepted in Username field 

### ISSUE THREAD

**Issue by nisha552** [Ripples2023/Ripples2023Repo-Sprint-5#64]
Test case: username field with special characters

Test data: 
"firstName": "Riya",
    "lastName":"Mishramishra",
    "email":"ryaa@gmail.com",
    "username":"mish@riyaa56",
    "password":"mamma2@919"

Message displayed: User Registered            
Status code:201Created

**Comment by Jebisha123** [comment]
Resolved

**Comment by nisha552** [comment]
Retest 
Working as expected
Close the issue
