### ISSUE TITLE
API Testing: While adding invalid credentials for login,response error is coming in Text format

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-5#65]
Hi @Jebisha123 ,

While adding invalid credentials,response error is coming in Text format

Steps to Reproduce:
1)Enter invalid username or password

Login will fail and error message is coming in text format instead of JSON

Screenshot attached:
![00](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/e83e548e-a143-4365-9825-a9bbb784b5a9)

**Comment by Jebisha123** [comment]
Resolved and updated code in github

**Comment by priyadhawan06** [comment]
![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/92e2d18d-16c9-4861-a8f7-1978272187ac)
 
Working fine.So,closing issue
