### ISSUE TITLE
API Testing:While adding valid credentials for login,response message is coming in Text format

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-5#66]
Hi @Jebisha123 ,

While adding invalid credentials,response error is coming in Text format

Steps to Reproduce:
1)Enter valid username or password

Login will be successful and
![01](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/75bbf3a4-46da-4959-81ea-333c943c4019)
 message is coming in text format instead of JSON

Screenshot attached:

**Comment by Jebisha123** [comment]
Resolved and updated code in github

**Comment by priyadhawan06** [comment]
![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/2a7349d4-5c5c-43b0-8cdc-a7f28c6feda9)

Working fine...so,closing this bug
