### ISSUE TITLE
API Testing:After successful registeration,message is coming in text format instead of JSON

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-5#67]
Hi @Jebisha123 ,

After successful registeration,message is coming in text format instead of JSON

Steps to Reproduce:
1)Enter valid inputs for all input fields

message is coming in text format instead of JSON

Screenshot attached:
![03](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/7777ccab-c3f8-43b8-8b28-753b630cc0ef)

**Comment by Jebisha123** [comment]
Resolved and updated in Github

**Comment by priyadhawan06** [comment]
![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/assets/148531903/a0a63b5b-8e4e-4a50-878a-58d437fbc23b)

Working fine.So,closing this issue.
