### ISSUE TITLE
API Testing - Respective error message not shown

### ISSUE THREAD

**Issue by SugiGitH** [Ripples2023/Ripples2023Repo-Sprint-5#69]
Objective : Validate invalid inputs in all the fields
Steps to reproduce : Enter Invalid inputs for firstname, lastname, username, email, password in the request body
Expected result : Error message for all the fields should appear
Actual result : Error message displayed only for Firstname, Lastname and Email

**Comment by Jebisha123** [comment]
Since password is encrypted,error message for everthing will be reflected except password length.

**Comment by SugiGitH** [comment]
Actual result : Error message displayed only for Firstname, Lastname and Email
-->Error message for username not displayed.

**Comment by SugiGitH** [comment]
Retested:
Expected result : Error message for all the fields should appear
Actual result:
result": {
        "firstName": "Invalid Input.FirstName Should contain only alphabets",
        "lastName": "Invalid Input.LastName should contain only alphabets",
        "email": "Invalid email",
        "username": "Invalid username.UserName should alphanumeric"
    }
