### ISSUE TITLE
API Testing - Error message not displayed for special characters in input fields

### ISSUE THREAD

**Issue by SugiGitH** [Ripples2023/Ripples2023Repo-Sprint-5#70]
Objective : Validate First Name,last name,Username should not contain Special characters

Steps to reproduce : 1)Enter valid inputs for email,password 
2)Enter special characters and numbers in first name, last name,Username field in the request body and Click on SEND

Expected result : "Firstname and Lastname should contains alphabets only and Username should be alphanumeric"

Actual result : Errors": {
        "lastName": "Invalid Input. Should contain only alphabets",
        "firstName": "Invalid Input. Should contain only alphabets"
    }

**Comment by Jebisha123** [comment]
Resolved

**Comment by SugiGitH** [comment]
Retested:
Expected result : "Firstname and Lastname should contains alphabets only and Username should be alphanumeric"
Actual result : 
result": {
        "lastName": "Invalid Input.LastName should contain only alphabets",
        "firstName": "Invalid Input.FirstName Should contain only alphabets",
        "username": "Invalid username.UserName should alphanumeric"
    }
