### ISSUE TITLE
API Testing - Password error message is not shown

### ISSUE THREAD

**Issue by SugiGitH** [Ripples2023/Ripples2023Repo-Sprint-5#71]
Objective : Verify Boundary value of all input fields

Steps to reproduce : 1)Enter inputs for firstname,lastname,username,email,password exceeding the maximum characters allowed in the request body

Expected result : "Firstname and Lastname should contains alphabets only and Username should be alphanumeric"

Actual result : Errors": {
        "lastName": "size must be between 0 and 20",
        "firstName": "size must be between 0 and 20",
        "email": "must match \"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,3}\"",
        "username": "size must be between 8 and 16"
    }

**Comment by Jebisha123** [comment]
when the size of the data is large,gets the error message for size.If size is correct then error message for alphabet,alphanumeric is displayed

**Comment by SugiGitH** [comment]
Corrected
