### ISSUE TITLE
API testing - Appropriate error message not displayed for Duplicate Email Id

### ISSUE THREAD

**Issue by SugiGitH** [Ripples2023/Ripples2023Repo-Sprint-5#72]
Objective : Verify unique email id

Steps to reproduce : 1)Enter valid inputs for firstname,lastname,username,password in the request body
2)Enter already registered emailid and click on SEND

Expected result : "Email id is already registered"

Actual result : Received the response "400:Bad request"
and the Response Body message as "User Already Exists"

**Comment by Jebisha123** [comment]
Resolved

**Comment by Jebisha123** [comment]
Resolved

**Comment by SugiGitH** [comment]
Retested:
Expected result : "Email id is already registered"
Actual result :
 "Message": "Email Already Exists"
