### ISSUE TITLE
User is able login with username "having special character"

### ISSUE THREAD

**Issue by reshuripple** [Ripples2023/Ripples2023Repo-Sprint-5#74]
As as user is able to sign up with username field contains special character.
And with same username  and password we are able to login successfully. 
[Error.docx](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/files/13577024/Error.docx)
attaching the screen shot for details.

**Comment by reshuripple** [comment]
Test Data:
{
"username":"sharma@bhavi",
"password":"bhaviji#$123"  
}

**Comment by Jebisha123** [comment]
Issue Resolved

**Comment by Jebisha123** [comment]
Resolved

**Comment by reshuripple** [comment]
tested and closing
