### ISSUE TITLE
User is able to login successfully with password field contains space

### ISSUE THREAD

**Issue by reshuripple** [Ripples2023/Ripples2023Repo-Sprint-5#75]
As user is able to sign up with password field contains space.
And with same username and password we are able to login successfully.
attaching the screen shot for details.
[Error.docx](https://github.com/Ripples2023/Ripples2023Repo-Sprint-5/files/13577252/Error.docx)
test data:
{

 "username":"mannysingh", 
"password":"Many ghg&%&"
}

**Comment by Jebisha123** [comment]
Resolved

**Comment by reshuripple** [comment]
tested and closing
